# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countersign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cs_process',
            name='file',
            field=models.FileField(default='blank', upload_to='./upload/', verbose_name='会签文件'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cs_process',
            name='ceo_approved',
            field=models.CharField(choices=[('1', '同意'), ('0', '不同意')], max_length=1),
        ),
        migrations.AlterField(
            model_name='cs_process',
            name='cfo_approved',
            field=models.CharField(choices=[('1', '同意'), ('0', '不同意')], max_length=1),
        ),
    ]
