# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0002_i18n'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sea',
            name='area',
            field=models.BigIntegerField(help_text='平方公里', verbose_name='area'),
        ),
    ]
