# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-29 09:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='备注'),
        ),
    ]
